### ISSUE TITLE
I can select disabled dates

### ISSUE THREAD

**Issue by logan-19** [dmuy/duDatepicker#13]
Hi, I have disabled dates `disabledDates: ['05 .01.2021-10.01.2021 ']` but I can still select these dates, it's sad, can I do something about it?
Thanks!

![1](https://user-images.githubusercontent.com/28824929/103432953-4c4ffc80-4be0-11eb-88fb-f110b36c901f.PNG)

**Comment by dmuy** [comment]
Hi @logan-19,

Sorry for the very late reply. Honestly, I don't know how to go over this one. Because technically, you're selecting dates which are not disabled, it's just that the disabled dates are within the range you selected. If you have any idea on how the date picker should behave in this scenario, do tell.

**Comment by dmuy** [comment]
Closing as inactive. Please open up a discussion if you want to talk more about this. Thanks
