### ISSUE TITLE
Datechange, different format

### ISSUE THREAD

**Issue by tatof** [dmuy/duDatepicker#5]
Hello,

Great plugin! 
Is it posible to get a different format back on "datechanged"?
Need a "database" ready format because I've got a language related bug in my php code.

Something like this:
`   $('#datepicker').duDatepicker({
            format: 'd mmmm yyyy',
            maxdate: 'today',
            auto: true
        }).on('datechanged', function(e){                        
            var thedate = e.date({format: 'd mm y'});
alert(thedate);
});`

**Comment by dmuy** [comment]
Hello @tatof ,

Thanks for using!

Actually there was a workaround I knew but it's kind of a "brute force" solution, so instead of doing that one I updated the code (latest commit) to facilitate setting a custom output format for the date in the `datechanged` event.

By default the `format` configuration will be used, but if you want to use another format you just need to specify `outFormat` in the initialization of the date picker.

Like so...
```javascript
$('#datepicker').duDatepicker({ format: 'd mmmm yyyy', outFormat: 'dd-mm-yyyy', maxdate: 'today', auto: true })
    .on('datechanged', function(e){ 
        console.log(e.date); // this will print in the console: '30-12-2018' for 30 December 2018
    });
```

**Comment by tatof** [comment]
Hey Dmuy,

Thanks! I fixed it with momentjs but this fix is ofcourse way beter and easier.
Going to change my code, thank you for the quick help.
